import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import * as vscode from "vscode";
import { getConfiguredProviders } from "./envHelper";

const LAMIA_HOME = path.join(os.homedir(), ".lamia");
const IDE_DIR = path.join(LAMIA_HOME, "ide");
const CHAT_CONFIG = path.join(IDE_DIR, "config.yaml");
const IDE_ADAPTERS_DIR = path.join(IDE_DIR, "extensions", "adapters");
const IDE_EXTENSIONS_DIR = path.join(IDE_DIR, "extensions");

export function getChatConfigPath(): string {
  return CHAT_CONFIG;
}

export function readSelectedModel(): string | null {
  try {
    const raw = fs.readFileSync(CHAT_CONFIG, "utf8");
    const match = raw.match(/- name:\s*"?([^"\n]+)"?/);
    return match ? match[1].trim() : null;
  } catch {
    return null;
  }
}

export function writeSelectedModel(model: string): void {
  fs.mkdirSync(IDE_DIR, { recursive: true });

  const providers = new Set(getConfiguredProviders());
  const modelProvider = providerFromModel(model);
  if (modelProvider) {
    providers.add(modelProvider);
  }

  const hasCustomAdapters = fs.existsSync(IDE_ADAPTERS_DIR) &&
    fs.readdirSync(IDE_ADAPTERS_DIR).some(f => f.endsWith(".py"));

  const lines = [
    "# Auto-generated by Lamia Studio — do not edit manually",
    "model_chain:",
    `  - name: "${model}"`,
    "    max_retries: 3",
    "",
    "providers:",
  ];

  for (const p of providers) {
    lines.push(`  ${p}:`);
    lines.push("    enabled: true");
  }
  lines.push("");

  if (hasCustomAdapters) {
    lines.push(`extensions_folder: "${IDE_EXTENSIONS_DIR}"`);
    lines.push("");
  }

  fs.writeFileSync(CHAT_CONFIG, lines.join("\n"), "utf8");
}

export function ensureChatConfig(): void {
  syncCustomAdapters();

  // Keep existing config in sync with discovered custom adapters.
  if (fs.existsSync(CHAT_CONFIG)) {
    ensureExtensionsFolderInConfig();
    return;
  }

  const providers = getConfiguredProviders();
  if (providers.length === 0) return;

  const defaultModels: Record<string, string> = {
    anthropic: "anthropic:claude-sonnet-4-20250514",
    openai: "openai:gpt-4o",
  };

  const primary = defaultModels[providers[0]] || `${providers[0]}:default`;
  writeSelectedModel(primary);
}

function providerFromModel(model: string): string | null {
  const parts = model.split(":");
  if (parts.length < 2) {
    return null;
  }
  const provider = parts[0].trim();
  return provider || null;
}

function hasCustomAdapters(): boolean {
  return fs.existsSync(IDE_ADAPTERS_DIR)
    && fs.readdirSync(IDE_ADAPTERS_DIR).some((f) => f.endsWith(".py"));
}

function ensureExtensionsFolderInConfig(): void {
  let raw: string;
  try {
    raw = fs.readFileSync(CHAT_CONFIG, "utf8");
  } catch {
    return;
  }

  const extLine = `extensions_folder: "${IDE_EXTENSIONS_DIR}"`;
  const hasLine = raw.includes("extensions_folder:");
  const shouldHaveLine = hasCustomAdapters();

  if (shouldHaveLine && !hasLine) {
    const next = raw.endsWith("\n")
      ? `${raw}${extLine}\n`
      : `${raw}\n${extLine}\n`;
    fs.writeFileSync(CHAT_CONFIG, next, "utf8");
    return;
  }

  if (!shouldHaveLine && hasLine) {
    const next = raw
      .split("\n")
      .filter((line) => !line.trimStart().startsWith("extensions_folder:"))
      .join("\n");
    fs.writeFileSync(CHAT_CONFIG, next, "utf8");
  }
}

/**
 * Extract the provider name from a Python adapter file by parsing the
 * ``def name(cls)`` classmethod return value.
 */
function extractProviderName(pyContent: string): string | null {
  const match = pyContent.match(
    /def\s+name\s*\(\s*cls\s*\)\s*(?:->\s*[^:]+)?\s*:[\s\S]*?return\s+["']([^"']+)["']/
  );
  return match ? match[1] : null;
}

/**
 * Copy custom adapter files from workspace ``extensions/adapters/`` folders
 * into ``~/.lamia/ide/extensions/adapters/``.  Each file is renamed to
 * ``{provider_name}.py`` where provider_name comes from the adapter's
 * ``name()`` classmethod.
 */
export function syncCustomAdapters(): void {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders) return;

  fs.mkdirSync(IDE_ADAPTERS_DIR, { recursive: true });

  for (const folder of folders) {
    const adapterDirs = discoverAdapterDirs(folder.uri.fsPath);
    for (const adapterDir of adapterDirs) {
      let entries: fs.Dirent[];
      try {
        entries = fs.readdirSync(adapterDir, { withFileTypes: true });
      } catch {
        continue;
      }

      for (const entry of entries) {
        if (!entry.isFile() || !entry.name.endsWith(".py") || entry.name.startsWith("_")) continue;

        const srcPath = path.join(adapterDir, entry.name);
        let content: string;
        try {
          content = fs.readFileSync(srcPath, "utf8");
        } catch {
          continue;
        }

        const providerName = extractProviderName(content);
        if (!providerName) continue;

        const destPath = path.join(IDE_ADAPTERS_DIR, `${providerName}.py`);
        try {
          fs.copyFileSync(srcPath, destPath);
        } catch {
          // Silently skip files that cannot be copied
        }
      }
    }
  }
}

function discoverAdapterDirs(root: string, maxDepth: number = 5): string[] {
  const dirs: string[] = [];
  const visited = new Set<string>();

  const walk = (dir: string, depth: number): void => {
    if (depth < 0) return;

    const directAdapterDir = path.join(dir, "extensions", "adapters");
    if (fs.existsSync(directAdapterDir)) {
      dirs.push(directAdapterDir);
    }

    if (depth === 0) return;

    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith(".") || entry.name === "node_modules" || entry.name === "__pycache__" || entry.name === "venv") continue;

      const child = path.join(dir, entry.name);
      if (visited.has(child)) continue;
      visited.add(child);
      walk(child, depth - 1);
    }
  };

  walk(root, maxDepth);
  return Array.from(new Set(dirs));
}
