import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { getConfiguredProviders } from "./envHelper";

const LAMIA_HOME = path.join(os.homedir(), ".lamia");
const IDE_DIR = path.join(LAMIA_HOME, "ide");
const CHAT_CONFIG = path.join(IDE_DIR, "config.yaml");

export function getChatConfigPath(): string {
  return CHAT_CONFIG;
}

export function readSelectedModel(): string | null {
  try {
    const raw = fs.readFileSync(CHAT_CONFIG, "utf8");
    const match = raw.match(/- name:\s*"?([^"\n]+)"?/);
    return match ? match[1].trim() : null;
  } catch {
    return null;
  }
}

export function writeSelectedModel(model: string): void {
  fs.mkdirSync(IDE_DIR, { recursive: true });

  const providers = new Set(getConfiguredProviders());
  const modelProvider = providerFromModel(model);
  if (modelProvider) {
    providers.add(modelProvider);
  }
  const lines = [
    "# Auto-generated by Lamia Studio — do not edit manually",
    "model_chain:",
    `  - name: "${model}"`,
    "    max_retries: 3",
    "",
    "providers:",
  ];

  for (const p of providers) {
    lines.push(`  ${p}:`);
    lines.push("    enabled: true");
  }
  lines.push("");

  fs.writeFileSync(CHAT_CONFIG, lines.join("\n"), "utf8");
}

export function ensureChatConfig(): void {
  if (fs.existsSync(CHAT_CONFIG)) return;

  const providers = getConfiguredProviders();
  if (providers.length === 0) return;

  const defaultModels: Record<string, string> = {
    anthropic: "anthropic:claude-sonnet-4-20250514",
    openai: "openai:gpt-4o",
  };

  const primary = defaultModels[providers[0]] || `${providers[0]}:default`;
  writeSelectedModel(primary);
}

function providerFromModel(model: string): string | null {
  const parts = model.split(":");
  if (parts.length < 2) {
    return null;
  }
  const provider = parts[0].trim();
  return provider || null;
}
