import * as vscode from "vscode";
import * as os from "os";
import * as fs from "fs";
import * as path from "path";
import { execFileSync } from "child_process";
import { getConfiguredProviders } from "./envHelper";

const LAMIA_HOME = path.join(os.homedir(), ".lamia");
const VENV_BIN = path.join(LAMIA_HOME, "venv", process.platform === "win32" ? "Scripts" : "bin");
const VENV_LAMIA = path.join(VENV_BIN, process.platform === "win32" ? "lamia.exe" : "lamia");
const LOCAL_EDITABLE_MARKER = path.join(LAMIA_HOME, "venv", ".lamia-ide-local-editable");

function safeExec(cmd: string, args: string[]): string {
  try {
    return execFileSync(cmd, args, { encoding: "utf8", timeout: 5000 }).trim();
  } catch {
    return "not found";
  }
}

function getLamiaVersion(): string {
  if (fs.existsSync(VENV_LAMIA)) {
    return safeExec(VENV_LAMIA, ["--version"]);
  }
  return safeExec("lamia", ["--version"]);
}

function getPythonVersion(): string {
  const cmd = process.platform === "win32" ? "python" : "python3";
  return safeExec(cmd, ["--version"]);
}

function getWorkspaceInfo(): string {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) return "no workspace open";
  return folders.map(f => f.uri.fsPath).join(", ");
}

function getActiveExtensions(): string {
  return vscode.extensions.all
    .filter(e => !e.id.startsWith("vscode.") && e.isActive)
    .map(e => `${e.id} (${e.packageJSON?.version ?? "?"})`)
    .slice(0, 20)
    .join("\n  ");
}

export async function collectSystemInfo(): Promise<string> {
  const ideVersion = vscode.version;
  const lamiaVersion = getLamiaVersion();
  const pythonVersion = getPythonVersion();
  const platform = `${os.platform()} ${os.release()} (${os.arch()})`;
  const workspace = getWorkspaceInfo();
  const providers = getConfiguredProviders();
  const extensions = getActiveExtensions();

  const pinnedVersionFile = path.join(__dirname, "..", "initial-lamia-version.txt");
  let initialVersion = "unknown";
  try {
    initialVersion = fs.readFileSync(pinnedVersionFile, "utf8").trim();
  } catch {}
  const localEditable = fs.existsSync(LOCAL_EDITABLE_MARKER);

  return [
    "## Lamia Studio System Info",
    "",
    `- **IDE Version**: ${ideVersion}`,
    `- **Lamia CLI Version**: ${lamiaVersion}`,
    `- **Lamia Install Mode**: ${localEditable ? "local editable source" : "bundled/pinned"}`,
    `- **Lamia Initial Version File**: ${initialVersion}`,
    `- **Python**: ${pythonVersion}`,
    `- **OS**: ${platform}`,
    `- **Workspace**: ${workspace}`,
    `- **Configured Providers**: ${providers.length > 0 ? providers.join(", ") : "none"}`,
    "",
    "**Active Extensions**:",
    `  ${extensions || "none"}`,
    "",
    "---",
    "*Generated by Lamia Studio — paste this into your issue report.*",
  ].join("\n");
}
